WebUI/Controllers/CountryController.cs
using System;
using System.Linq;
using System.Web.Mvc;

using Omu.AwesomeMvc;
using Omu.ProDinner.Core;
using Omu.ProDinner.Core.Model;
using Omu.ProDinner.Core.Service;
using Omu.ProDinner.WebUI.Mappers;
using Omu.ProDinner.WebUI.Utils;
using Omu.ProDinner.WebUI.ViewModels.Input;

namespace Omu.ProDinner.WebUI.Controllers
{
    public class CountryController : Cruder<Country, CountryInput>
    {
        public CountryController(ICrudService<Country> service, IProMapper v)
            : base(service, v)
        {
        }

        [HttpPost]
        public ActionResult BatchRestore(int[] ids)
        {
            if (WebUtils.IsUserAdmin())
            {
                service.BatchRestore(ids);
            }

            return Json(new { });
        }

        public ActionResult BatchDelete(int[] ids)
        {
            return PartialView(new BatchDeleteConfirmInput { Ids = ids });
        }

        [HttpPost]
        public ActionResult BatchDelete(BatchDeleteConfirmInput input)
        {
            service.BatchDelete(input.Ids);
            return Json(new { });
        }

        [HttpPost]
        public ActionResult GridGetItems(GridParams g, string parent, bool? restore)
        {
            var isAdmin = WebUtils.IsUserAdmin();

            var data = service.Where(o => o.Name.StartsWith(parent), isAdmin);

            if (restore.HasValue && isAdmin)
            {
                service.Restore(Convert.ToInt32(g.Key));
            }

            var model = new GridModelBuilder<Country>(data.AsQueryable(), g)
            {
                Key = "Id",
                Map = MapEntityToGridModel,
                GetItem = () => service.Get(Convert.ToInt32(g.Key))
            }.Build();

            return Json(model);
        }

        /// <summary>
        /// view name for CountryLookup to render items
        /// </summary>
        protected override string RowViewName
        {
            get
            {
                return "ListItems/Country";
            }
        }
    }
}

WebUI/Controllers/DinnerController.cs
using System;
using System.Linq;
using System.Web.Mvc;

using Omu.AwesomeMvc;
using Omu.ProDinner.Core.Model;
using Omu.ProDinner.Core.Service;
using Omu.ProDinner.WebUI.Mappers;
using Omu.ProDinner.WebUI.Utils;
using Omu.ProDinner.WebUI.ViewModels.Input;

namespace Omu.ProDinner.WebUI.Controllers
{
    public class DinnerController : Cruder<Dinner, DinnerInput>
    {
        public DinnerController(ICrudService<Dinner> service, IProMapper mapper)
            : base(service, mapper)
        {
        }

        protected override object MapEntityToGridModel(Dinner o)
        {
            return new
                {
                    o.Id, 
                    o.IsDeleted, 
                    o.Name,
                    CountryName = o.Country.Name,
                    ChefName = o.Chef.FirstName + " " + o.Chef.LastName,
                    o.Address,
                    MealsCount = o.Meals.Count
                };
        }

        [HttpPost]
        public ActionResult GridGetItems(GridParams g, string parent, bool? restore)
        {
            var isAdmin = WebUtils.IsUserAdmin();

            var data = service.Where(o => o.Name.Contains(parent), isAdmin);

            if (restore.HasValue && isAdmin)
            {
                service.Restore(Convert.ToInt32(g.Key));
            }

            var model = new GridModelBuilder<Dinner>(data.AsQueryable(), g)
                {
                    Key = "Id",
                    Map = MapEntityToGridModel,
                    GetItem = () => service.Get(Convert.ToInt32(g.Key))
                }.Build();

            return Json(model);
        }

        public ActionResult Details(int key)
        {
            var dinner = service.Get(key);
            return View(dinner);
        }
    }
}

WebUI/Controllers/FeedbackController.cs
using System.Web.Mvc;

using Omu.ProDinner.Core.Model;
using Omu.ProDinner.Core.Repository;
using Omu.ProDinner.WebUI.Utils;
using Omu.ProDinner.WebUI.ViewModels.Input;
using Omu.ValueInjecter;

namespace Omu.ProDinner.WebUI.Controllers
{
    public class FeedbackController : Controller
    {
        private readonly IRepo<Feedback> repo;

        public FeedbackController(IRepo<Feedback> repo)
        {
            this.repo = repo;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create()
        {
            return View(new FeedbackInput());
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(FeedbackInput input)
        {
            if (!ModelState.IsValid)
            {
                return View(input);
            }

            input.Comments = HtmlUtil.SanitizeHtml(input.Comments);
            
            var feedback = new Feedback { Comments = input.Comments };
            feedback = repo.Insert(feedback);
            repo.Save();

            Session["lastFeedback"] = feedback.Id;
            return Json(new { });
        }

        public ActionResult Edit(int id)
        {
            return View("Create", new FeedbackInput().InjectFrom(repo.Get(id)));
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(FeedbackInput input)
        {
            if (!ModelState.IsValid)
            {
                return View("Create", input);
            }

            var feedback = repo.Get(input.Id);
            feedback.Comments = HtmlUtil.SanitizeHtml(input.Comments);
            repo.Save();

            return Json(new { });
        }
    }
}

WebUI/Controllers/MealController.cs
using System;
using System.Web;
using System.Web.Mvc;
using Omu.AwesomeMvc;
using Omu.ProDinner.Core.Model;
using Omu.ProDinner.Core.Service;
using Omu.ProDinner.WebUI.Mappers;
using Omu.ProDinner.WebUI.ViewModels.Input;

namespace Omu.ProDinner.WebUI.Controllers
{
    public class MealController : Cruder<Meal, MealInput>
    {
        private new readonly IMealService service;
        private readonly IFileManagerService fileManagerService;

        public MealController(IMealService service, IProMapper mapper, IFileManagerService fileManagerService)
            : base(service, mapper)
        {
            this.service = service;
            this.fileManagerService = fileManagerService;
        }

        public override ActionResult Index()
        {
            return View();
        }

        protected override string RowViewName
        {
            get { return "ListItems/Meal"; }
        }
        
        public ActionResult GetMeal(int id)
        {
            return Json(new { Id = id, Content = this.RenderView(RowViewName, new[] { service.Get(id) }) });
        }

        [HttpPost]
        public ActionResult Upload(HttpPostedFileBase file)
        {
            int w, h;
            var name = fileManagerService.SaveTempJpeg(Globals.PicturesPath, file.InputStream, out w, out h);
            return Json(new {name, type = file.ContentType, size = file.ContentLength, w, h});
        }

        public ActionResult ChangePicture(int id)
        {
            return View(service.Get(id));
        }

        [HttpPost]
        public ActionResult Crop(int x, int y, int w, int h, string filename, int id)
        {
            service.SetPicture(id, Globals.PicturesPath, filename, x, y, w, h);
            return Json(new {name = filename});
        }

        #region used only by browsers that don't support drag and drop upload

        public ActionResult OChangePicture(int id)
        {
            return View(service.Get(id));
        }

        [HttpPost]
        public ActionResult OChangePicture()
        {
            var file = Request.Files["fileUpload"];
            var id = Convert.ToInt32(Request.Form["id"]);

            if (file.ContentLength > 0)
            {
                int w, h;
                var name = fileManagerService.SaveTempJpeg(Globals.PicturesPath, file.InputStream, out w, out h);
                return RedirectToAction("ocrop",
                                        new CropInput {ImageWidth = w, ImageHeight = h, Id = id, FileName = name});
            }

            return RedirectToAction("Index");
        }

        public ActionResult OCrop(CropInput cropDisplay)
        {
            return View(cropDisplay);
        }

        [HttpPost]
        public ActionResult OCrop(int x, int y, int w, int h, int id, string filename)
        {
            service.SetPicture(id, Globals.PicturesPath, filename, x, y, w, h);
            return RedirectToAction("ochangepicture", new {id});
        }

        #endregion
        
    }
}

WebUI/Views/Shared/ListItems/Country.cshtml
@using Omu.ProDinner.WebUI.ViewModels.Display
@model IEnumerable<Country>
@foreach (var o in Model)
{
    <li class="awe-li" data-val="@(o.Id)" style="position: relative;"> @* data-val required by the lookup, used to select item *@
    @o.Name
        <div class="act">
            <button class="awe-btn" onclick="awe.open('editLookupCountry', { params: { id: @(o.Id) }})">
                <span class="ico-edit"></span>
            </button>
            &nbsp;
            @Html.Partial("deletebtn", new DelBtn { Id = o.Id, IsDeleted = o.IsDeleted, Name = "LookupCountry" })
        </div>
    </li>
}

WebUI/Views/Shared/ListItems/Dinner.cshtml
@using System.Threading
@using Omu.ProDinner.WebUI.ViewModels.Display
@model IEnumerable<Dinner>

@{
    var dtformat = Thread.CurrentThread.CurrentCulture.DateTimeFormat;
    var format = dtformat.ShortDatePattern + " " + dtformat.ShortTimePattern;
}
@foreach (var o in Model)
{
    <li data-val='@(o.Id)' class="awe-li dinner">
<div class="fr">    
@Html.Partial("deletebtn", new DelBtn { Id = o.Id, IsDeleted = o.IsDeleted, Name = "Dinner" })
    </div>
    <div class="fl">
        @o.Name</div>
    <div class="fr">
        @o.Chef.FirstName
        @o.Chef.LastName
        @Mui.from
        @o.Chef.Country.Name
        @Mui.is_cooking&nbsp;</div>
        
    <br class="cbt" />
    @foreach (var m in o.Meals)
    {
        <img src='@Url.Content("~/pictures/Meals/s" + (m.Picture ?? "0.jpg"))' class="sthumb" alt='@m.Name' />
    }
    <br class="cbt" />    
    <div class="fl">
        @o.Country.Name,
        @o.Address</div>        
        <div class="fr">
            <button type="button" class="awe-btn" onclick="awe.open('editDinner', { params:{ id: @(o.Id) }})">
                <span class=" ico-edit"></span>
            </button>
        </div>    
        <div class="fr" style="margin-right: 1em;">
            @Mui.Start @(o.Start.ToString(format)) @Mui.End @(o.End.ToString(format)) 
        </div> 
    <br class="cbt" />    
</li>
}

WebUI/Views/Shared/ListItems/Feedback.cshtml
@model IEnumerable<Feedback>
@{
    var id = 0;
    if(Session["lastFeedback"] != null)
    {
        id = (int)Session["lastFeedback"];
    }
}

@foreach (var o in Model)
{
    <li class="awe-li feedback" data-val="@o.Id">
        <div>
            @Html.Raw(o.Comments)
        </div>
        <div class="fr">
            @{ if(id == o.Id)
               {
        <button class="awe-btn" onclick="@(Url.Awe().PopupFormAction()
        .Url(Url.Action("Edit", "Feedback", new { o.Id }))
        .Success("reload").Height(500).Width(900))">
                Edit</button> 
               }
            }
        </div>
    </li>
} 

WebUI/Views/Shared/ListItems/Meal.cshtml
@using Omu.ProDinner.WebUI.ViewModels.Display
@model IEnumerable<Meal>
@foreach (var o in Model)
{
    <li data-val='@(o.Id)' class="awe-li meal awe-il">
        <div>@o.Name
            <div class="fr">
                @Html.Partial("deletebtn", new DelBtn { Id = o.Id, IsDeleted = o.IsDeleted, Name = "Meal" })
            </div>
        </div>
        <div>
            <div class="fl">
                <img  src='@Url.Content("~/pictures/Meals/" + (string.IsNullOrEmpty(o.Picture) ? "0.jpg" : o.Picture))' class="thumb"  alt='picture' /></div>
            <div class="comments">@o.Comments</div>
            <br class="cbt" />
        </div>
        <div class="cbt" style="margin-top: 0.5em;">
            <div class='cool fl'>
                <button type="button" class="awe-btn" onclick="awe.open('changePicture', { params: { id: @(o.Id) }})" style="padding:0.1em 0.3em">@Mui.change_picture</button>
            </div>
            <div class='notcool fl'>                
                <button type="button" class="awe-btn" onclick="location.href='@Url.Action("ochangepicture", "Meal", new { o.Id })'">@Mui.change_picture</button>
            </div>
            <div class="fr">
                <button type="button" class="awe-btn" onclick="awe.open('editMeal', { params:{ id:  @(o.Id) } })" style="padding:0.1em 0.3em">
                    <span class="ico-edit"></span>
                </button>
            </div>
        </div>
    </li>
}

WebUI/Views/Shared/ListItems/MealItem.cshtml
@model IEnumerable<Meal>
@foreach (var o in Model)
{
    <li class="awe-li mealitem awe-il" data-val="@o.Id">
        <div>
            <button class="awe-btn awe-movebtn mealmove">
                <span class="awe-icon"></span>
            </button>
            @o.Name
        </div>
        <img  src='@Url.Content("~/pictures/Meals/" + (string.IsNullOrEmpty(o.Picture) ? "0.jpg" : o.Picture))' class="thumb"  alt='picture' />
    </li>
}