WebUI/Controllers/Awesome/Lookup/CountryIdLookupController.cs
using System.Linq;
using System.Web.Mvc;

using Omu.AwesomeMvc;
using Omu.ProDinner.Core.Model;
using Omu.ProDinner.Core.Repository;
using Omu.ProDinner.WebUI.Utils;

namespace Omu.ProDinner.WebUI.Controllers.Awesome.Lookup
{
    public class CountryIdLookupController : Controller
    {
        private readonly IRepo<Country> repo;

        public CountryIdLookupController(IRepo<Country> repo)
        {
            this.repo = repo;
        }

        public ActionResult SearchForm()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Search(string search, int page)
        {
            var list = repo.Where(o => o.Name.StartsWith(search), WebUtils.IsUserAdmin())
                .OrderByDescending(o => o.Id);

            return Json(new AjaxListResult
            {
                Content = this.RenderView("ListItems/Country", list.Page(page, 10).ToList()),
                More = list.Count() > page * 10
            });
        }

        public ActionResult GetItem(int v)
        {
            var c = repo.Get(v) ?? new Country();
            return Json(new KeyContent(c.Id, c.Name));
        }
    }
}

WebUI/Controllers/CountryController.cs
using System;
using System.Linq;
using System.Web.Mvc;

using Omu.AwesomeMvc;
using Omu.ProDinner.Core;
using Omu.ProDinner.Core.Model;
using Omu.ProDinner.Core.Service;
using Omu.ProDinner.WebUI.Mappers;
using Omu.ProDinner.WebUI.Utils;
using Omu.ProDinner.WebUI.ViewModels.Input;

namespace Omu.ProDinner.WebUI.Controllers
{
    public class CountryController : Cruder<Country, CountryInput>
    {
        public CountryController(ICrudService<Country> service, IProMapper v)
            : base(service, v)
        {
        }

        [HttpPost]
        public ActionResult BatchRestore(int[] ids)
        {
            if (WebUtils.IsUserAdmin())
            {
                service.BatchRestore(ids);
            }

            return Json(new { });
        }

        public ActionResult BatchDelete(int[] ids)
        {
            return PartialView(new BatchDeleteConfirmInput { Ids = ids });
        }

        [HttpPost]
        public ActionResult BatchDelete(BatchDeleteConfirmInput input)
        {
            service.BatchDelete(input.Ids);
            return Json(new { });
        }

        [HttpPost]
        public ActionResult GridGetItems(GridParams g, string parent, bool? restore)
        {
            var isAdmin = WebUtils.IsUserAdmin();

            var data = service.Where(o => o.Name.StartsWith(parent), isAdmin);

            if (restore.HasValue && isAdmin)
            {
                service.Restore(Convert.ToInt32(g.Key));
            }

            var model = new GridModelBuilder<Country>(data.AsQueryable(), g)
            {
                Key = "Id",
                Map = MapEntityToGridModel,
                GetItem = () => service.Get(Convert.ToInt32(g.Key))
            }.Build();

            return Json(model);
        }

        /// <summary>
        /// view name for CountryLookup to render items
        /// </summary>
        protected override string RowViewName
        {
            get
            {
                return "ListItems/Country";
            }
        }
    }
}

WebUI/Views/CountryIdLookup/SearchForm.cshtml
@{
    Layout = null;
}

@(Html.Awe().InitPopupForm()
            .Name("createLookupCountry")
            .Url(Url.Action("Create","Country"))
            .Parameter("usingAjaxList", true)
            .Success("utils.lookupCreated")
            .Modal(true)
            .Height(200))

@(Html.Awe().InitPopupForm()
            .Name("editLookupCountry")
            .Url(Url.Action("Edit","Country"))
            .Parameter("usingAjaxList", true)
            .Success("utils.lookupEdited('Id')")
            .Modal(true)
            .Height(200))

@(Html.Awe().InitPopupForm()
            .Name("deleteLookupCountry")
            .Url(Url.Action("Delete","Country"))
            .Parameter("usingAjaxList", true)
            .Success("utils.lookupDeleted('Id')")
            .Modal(true)
            .Height(200))

@(Html.Awe().InitCall("restoreLookupCountry")
            .Url(Url.Action("Restore","Country"))
            .Success("utils.lookupEdited('Id')"))

<div class="einput">
    <input type="text" name="search" class="awe-searchtxt" placeholder="search..." /></div>
<button type="button" class="awe-searchbtn awe-btn">Search</button>
<button type="button" class="awe-btn mbtn" onclick="awe.open('createLookupCountry')">Create</button>

WebUI/Views/CountryIdLookup/item.cshtml
@model Country
<li data-value='@Model.Id'>
@Model.Name
</li>