WebUI/Controllers/ChefController.cs
using System;
using System.Linq;
using System.Web.Mvc;

using Omu.AwesomeMvc;
using Omu.ProDinner.Core.Model;
using Omu.ProDinner.Core.Repository;
using Omu.ProDinner.Core.Service;
using Omu.ProDinner.WebUI.Mappers;
using Omu.ProDinner.WebUI.Utils;
using Omu.ProDinner.WebUI.ViewModels.Input;

namespace Omu.ProDinner.WebUI.Controllers
{
    public class ChefController : Cruder<Chef, ChefInput>
    {
        private readonly IRepo<Chef> chefRepo;

        public ChefController(ICrudService<Chef> service, IProMapper mapper, IRepo<Chef> chefRepo)
            : base(service, mapper)
        {
            this.chefRepo = chefRepo;
        }

        protected override object MapEntityToGridModel(Chef chef)
        {
            return new { chef.Id, chef.FirstName, chef.LastName, Country = chef.Country.Name, chef.IsDeleted };
        }

        [HttpPost]
        public ActionResult GridGetItems(GridParams g, string parent, bool? restore)
        {
            var isAdmin = WebUtils.IsUserAdmin();

            var data = chefRepo.Where(o => o.FirstName.StartsWith(parent) || o.LastName.StartsWith(parent), isAdmin);

            if (restore.HasValue && isAdmin)
            {
                service.Restore(Convert.ToInt32(g.Key));
            }

            var model = new GridModelBuilder<Chef>(data.AsQueryable(), g)
                    {
                        Key = "Id",
                        Map = MapEntityToGridModel,
                        GetItem = () => chefRepo.Get(Convert.ToInt32(g.Key))
                    }.Build();

            return Json(model);
        }
    }
}

WebUI/Controllers/DinnerController.cs
using System;
using System.Linq;
using System.Web.Mvc;

using Omu.AwesomeMvc;
using Omu.ProDinner.Core.Model;
using Omu.ProDinner.Core.Service;
using Omu.ProDinner.WebUI.Mappers;
using Omu.ProDinner.WebUI.Utils;
using Omu.ProDinner.WebUI.ViewModels.Input;

namespace Omu.ProDinner.WebUI.Controllers
{
    public class DinnerController : Cruder<Dinner, DinnerInput>
    {
        public DinnerController(ICrudService<Dinner> service, IProMapper mapper)
            : base(service, mapper)
        {
        }

        protected override object MapEntityToGridModel(Dinner o)
        {
            return new
                {
                    o.Id, 
                    o.IsDeleted, 
                    o.Name,
                    CountryName = o.Country.Name,
                    ChefName = o.Chef.FirstName + " " + o.Chef.LastName,
                    o.Address,
                    MealsCount = o.Meals.Count
                };
        }

        [HttpPost]
        public ActionResult GridGetItems(GridParams g, string parent, bool? restore)
        {
            var isAdmin = WebUtils.IsUserAdmin();

            var data = service.Where(o => o.Name.Contains(parent), isAdmin);

            if (restore.HasValue && isAdmin)
            {
                service.Restore(Convert.ToInt32(g.Key));
            }

            var model = new GridModelBuilder<Dinner>(data.AsQueryable(), g)
                {
                    Key = "Id",
                    Map = MapEntityToGridModel,
                    GetItem = () => service.Get(Convert.ToInt32(g.Key))
                }.Build();

            return Json(model);
        }

        public ActionResult Details(int key)
        {
            var dinner = service.Get(key);
            return View(dinner);
        }
    }
}

WebUI/Controllers/MealController.cs
using System;
using System.Web;
using System.Web.Mvc;
using Omu.AwesomeMvc;
using Omu.ProDinner.Core.Model;
using Omu.ProDinner.Core.Service;
using Omu.ProDinner.WebUI.Mappers;
using Omu.ProDinner.WebUI.ViewModels.Input;

namespace Omu.ProDinner.WebUI.Controllers
{
    public class MealController : Cruder<Meal, MealInput>
    {
        private new readonly IMealService service;
        private readonly IFileManagerService fileManagerService;

        public MealController(IMealService service, IProMapper mapper, IFileManagerService fileManagerService)
            : base(service, mapper)
        {
            this.service = service;
            this.fileManagerService = fileManagerService;
        }

        public override ActionResult Index()
        {
            return View();
        }

        protected override string RowViewName
        {
            get { return "ListItems/Meal"; }
        }
        
        public ActionResult GetMeal(int id)
        {
            return Json(new { Id = id, Content = this.RenderView(RowViewName, new[] { service.Get(id) }) });
        }

        [HttpPost]
        public ActionResult Upload(HttpPostedFileBase file)
        {
            int w, h;
            var name = fileManagerService.SaveTempJpeg(Globals.PicturesPath, file.InputStream, out w, out h);
            return Json(new {name, type = file.ContentType, size = file.ContentLength, w, h});
        }

        public ActionResult ChangePicture(int id)
        {
            return View(service.Get(id));
        }

        [HttpPost]
        public ActionResult Crop(int x, int y, int w, int h, string filename, int id)
        {
            service.SetPicture(id, Globals.PicturesPath, filename, x, y, w, h);
            return Json(new {name = filename});
        }

        #region used only by browsers that don't support drag and drop upload

        public ActionResult OChangePicture(int id)
        {
            return View(service.Get(id));
        }

        [HttpPost]
        public ActionResult OChangePicture()
        {
            var file = Request.Files["fileUpload"];
            var id = Convert.ToInt32(Request.Form["id"]);

            if (file.ContentLength > 0)
            {
                int w, h;
                var name = fileManagerService.SaveTempJpeg(Globals.PicturesPath, file.InputStream, out w, out h);
                return RedirectToAction("ocrop",
                                        new CropInput {ImageWidth = w, ImageHeight = h, Id = id, FileName = name});
            }

            return RedirectToAction("Index");
        }

        public ActionResult OCrop(CropInput cropDisplay)
        {
            return View(cropDisplay);
        }

        [HttpPost]
        public ActionResult OCrop(int x, int y, int w, int h, int id, string filename)
        {
            service.SetPicture(id, Globals.PicturesPath, filename, x, y, w, h);
            return RedirectToAction("ochangepicture", new {id});
        }

        #endregion
        
    }
}

WebUI/Controllers/UserController.cs
using System;
using System.Linq;
using System.Web.Mvc;

using Omu.AwesomeMvc;
using Omu.ProDinner.Core.Model;
using Omu.ProDinner.Core.Service;
using Omu.ProDinner.WebUI.Mappers;
using Omu.ProDinner.WebUI.Utils;
using Omu.ProDinner.WebUI.ViewModels.Input;

namespace Omu.ProDinner.WebUI.Controllers
{
    [Authorize(Roles = "admin")]
    public class UserController : Crudere<User, UserCreateInput, UserEditInput>
    {
        private new readonly IUserService service;

        public UserController(IProMapper mapper, IUserService service)
            : base(service, mapper)
        {
            this.service = service;
        }

        protected override object MapEntityToGridModel(User user)
        {
            return new
                    {
                        user.Id,
                        user.IsDeleted,
                        user.Login,
                        Roles = string.Join(", ", user.Roles.Select(o => o.Name))
                    };
        }

        [HttpPost]
        public ActionResult GridGetItems(GridParams g, string parent, bool? restore)
        {
            var isAdmin = WebUtils.IsUserAdmin();

            var data = service.Where(o => o.Login.StartsWith(parent), isAdmin);

            if (restore.HasValue && isAdmin)
            {
                service.Restore(Convert.ToInt32(g.Key));
            }

            var model = new GridModelBuilder<User>(data.AsQueryable(), g)
            {
                Key = "Id",
                Map = MapEntityToGridModel,
                GetItem = () => service.Get(Convert.ToInt32(g.Key))
            }.Build();

            return Json(model);
        }

        public ActionResult ChangePassword(int id)
        {
            return View();
        }

        [HttpPost]
        public ActionResult ChangePassword(ChangePasswordInput input)
        {
            if (!ModelState.IsValid) return View(input);
            service.ChangePassword(input.Id, input.Password);
            return Json(new { Login = service.Get(input.Id).Login });
        }
    }
}

WebUI/Views/Shared/ConfirmDelete.cshtml
@model DeleteConfirmInput
@using (Html.BeginForm())
{
    @Html.Raw(Model.Message)
}

@*used by the popupform .OnLoad func*@
<input type="hidden" name="key" value="@(Model.Id)" />

WebUI/Views/Shared/_Layout.cshtml
@using System.Threading
@using System.Web.Optimization
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
        @ViewBag.Title - ProDinner ASP.net MVC Awesome Demo Application
    </title>
    <link rel="shortcut icon" href="@Url.Content("~/favicon.ico")" type="image/x-icon" />
    @{
        var settings = SettingsController.ReadSettings(HttpContext.Current.Request);
    }
    
    <link href="//code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.min.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
    <link href="@Url.Content("~/Content/themes/" + settings.Theme + "/AwesomeMvc.css")?v=101" rel="stylesheet" type="text/css" id="aweStyle" />
    <link href="@Url.Content("~/Content/themes/" + settings.Theme + "/mods.css")?v=101" rel="stylesheet" type="text/css" id="modsStyle" />
    <link href="@Url.Content("~/Content/Common.css")?v=101" rel="stylesheet" type="text/css" />

    <script type="text/javascript" src="//code.jquery.com/jquery-1.11.0.min.js"></script>
    <script>
        var slinks = [
        { K: "@Url.Action("Index", "Chef")", C: "@Mui.Chef" },
        { K: "@Url.Action("Index", "Country")", C: "@Mui.Country" },
        { K: "@Url.Action("Index", "Dinner")", C: "Dinners" },
        { K: "@Url.Action("Index", "Feedback")", C: "Feedback" }
        ];
    </script>
</head>
    <body class="@settings.Theme">
        <noscript>
            <div id="nos">
                this site works best with javascript allowed
            </div>
        </noscript>
        <div id="header">
            <div class="cont">
                <ul class="menu">
                    <li><a id='logo' href="@Url.Content("~")"><i></i></a></li>
                    <li class="optional">@Html.ActionLink(Mui.Home, "Index", "Home")</li>
                    <li>@Html.ActionLink(Mui.Meals, "Index", "Meal")</li>
                    @if (WebUtils.IsUserAdmin())
                    {
                        <li>@Html.ActionLink("Users", "Index", "User")</li>
                    }
                    <li>@(Html.Awe().AjaxRadioList("ddlStuff")
                                    .DataFunc("utils.getItems(slinks)")
                                    .MenuDropdown(o => o.Caption(Mui.Stuff)))</li>
                    <li>@(Html.Awe().PopupActionLink().LinkText(Mui.About).Url(Url.Action("About", "Home")).Fullscreen(true).Modal(true).LoadOnce(true))</li>
                </ul>
                <ul class="menu" style="float: right;">
                    <li>@Html.Partial("login")</li>
                </ul>
            </div>
        </div>
        <div id="main" class="cont">
            <div class="awe-il settings">
                <button type="button" id="chDog" class="awe-btn mbtn2">hide dog</button>
                @Html.Action("Index", "Settings")
            </div>

            @RenderBody()
        </div>
        <div id="footer">
            <div class="cont">
                <span><a href='http://prodinner.codeplex.com'>project home: http://prodinner.codeplex.com</a></span>
            </div>
        </div>
        @Html.Partial("doghelp")
        <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.13.0/jquery.validate.min.js" type="text/javascript"></script>
        @Scripts.Render("~/bundle/Scripts/js")

        <script type="text/javascript">
            var root = '@(Url.Content("~"))';
            var isMobileOrTablet = '@(ClientSideUtils.IsMobileOrTablet())' == "True";
            var dateFormat = '@(AweUtil.ConvertTojQueryDateFormat(Thread.CurrentThread.CurrentCulture.DateTimeFormat.ShortDatePattern))';
            awem.clientDict = @Html.Raw(Json.Encode(ClientSideUtils.GetClientDict()));
            awem.isMobileOrTablet = function () { return isMobileOrTablet; };
            if (isMobileOrTablet) awe.popup = awem.bootstrapPopup;
                
            utils.init(dateFormat, isMobileOrTablet);
            awe.gmd = [awem.gridLoading, awem.gridPageInfo];// set global grid mods
            
            var controller = '@(ViewContext.RouteData.Values["Controller"].ToString().ToLower())';
            var action = '@(ViewContext.RouteData.Values["Action"].ToString().ToLower())';
            $(function () {
                documentReady(root, controller, action);
            });
        </script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/json2/20140204/json2.min.js" type="text/javascript" async></script>
        <script type="text/javascript" src="//code.jquery.com/ui/1.11.1/jquery-ui.min.js"></script>
        <script src="http://ajax.aspnetcdn.com/ajax/mvc/5.1/jquery.validate.unobtrusive.min.js" type="text/javascript"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
        <script type='text/javascript'>
            $.fn.bootstrapBtn = $.fn.button.noConflict();
        </script>
    </body>
</html>

WebUI/Views/Shared/deletebtn.cshtml
@model Omu.ProDinner.WebUI.ViewModels.Display.DelBtn
@if (Model.IsDeleted)
{
    <button type="button" class="awe-btn" onclick="awe.oc('restore@(Model.Name)', { params: { id: @(Model.Id) } })">
        <span class="ico-restore"></span>
    </button>
}
else
{
    <button type="button" class="awe-btn" onclick="awe.open('delete@(Model.Name)', { params: { id: @(Model.Id) } })">
        <span class="ico-del"></span>
    </button>
}

WebUI/Views/Shared/doghelp.cshtml
<div id="dogh">
</div>
<div id="tip">
    <div id="tipcontent">
    hi, click on the message to show more tips; click on me to hide
    </div>
</div>

WebUI/Views/Shared/login.cshtml
@if (HttpContext.Current.User.Identity.IsAuthenticated)
{
    <span class="optional" style="vertical-align: middle;">Welcome</span>
    <span style="vertical-align: middle;">@HttpContext.Current.User.Identity.Name</span>
    @Html.ActionLink("Log out", "SignOff", "account")
}
else
{
    @Html.ActionLink("log in", "SignIn", "account")
}